import React, { useEffect, useMemo, useState } from 'react';
import {
  Building2,
  Car,
  Coffee,
  Dumbbell,
  Loader2,
  Navigation2,
  Route,
  Scissors,
  ShoppingBag,
  Stethoscope,
  Store,
  Trash2,
  UtensilsCrossed,
  WifiOff,
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import ActiveRouteRunner, { readStoredActiveRouteId } from './ActiveRouteRunner';
import { HousePin, RouteSession, RouteStop } from './types';
import { RouteData, useGoogleMapsRouting } from '@/hooks/useGoogleMapsRouting';
import { calculateRouteDistance, optimizeRouteOrder } from '@/utils/routeOptimizer';
import { publishD2DRoute, removeD2DRoute, subscribeD2DRoutes } from '@/utils/d2dRouteBus';
import {
  d2dRouteUpdatedAtMs,
  loadD2DCloudRouteState,
  subscribeD2DCloudRouteChanges,
} from '@/utils/d2dCloud';
import { routeProgressBreakdown } from '@/utils/d2dRouteRuntime';
import { readD2DSyncStatus, subscribeD2DSyncStatus } from '@/utils/d2dSyncStatus';

interface RouteManagerProps {
  pins: HousePin[];
  onUpdatePin: (pinId: string, updates: Partial<HousePin>) => void;
}

const storefrontTypes = [
  { value: 'nail-salon', label: 'Nail Salon', icon: Scissors },
  { value: 'restaurant', label: 'Restaurant', icon: UtensilsCrossed },
  { value: 'retail', label: 'Retail Store', icon: ShoppingBag },
  { value: 'coffee-shop', label: 'Coffee Shop', icon: Coffee },
  { value: 'hair-salon', label: 'Hair Salon', icon: Scissors },
  { value: 'gym', label: 'Gym/Fitness', icon: Dumbbell },
  { value: 'medical', label: 'Medical/Dental', icon: Stethoscope },
  { value: 'automotive', label: 'Automotive', icon: Car },
  { value: 'office', label: 'Office', icon: Building2 },
  { value: 'other', label: 'Other', icon: Store },
];

const readLocalRoutes = (): RouteSession[] => {
  if (typeof window === 'undefined') return [];
  try {
    const parsed = JSON.parse(localStorage.getItem('routes') || '[]');
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
};

const normalizeAddress = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

const routeSourceLabel = (route: RouteSession) => {
  if (route.source === 'auto-street' || route.autoGenerated) return 'Auto street';
  if (route.source === 'storefront') return 'Storefront';
  if (route.source === 'gps-session') return route.parentRouteId ? 'Route history' : 'Field session';
  return 'Manual';
};

const mergeRouteSet = (
  previous: RouteSession[],
  cloudRoutes: RouteSession[],
  tombstones: Array<{ clientRouteId: string; updatedAt: string }>,
) => {
  const tombstoneById = new Map(tombstones.map((item) => [item.clientRouteId, new Date(item.updatedAt).getTime()]));
  let next = previous.filter((route) => {
    const deletedAt = tombstoneById.get(route.id);
    return deletedAt === undefined || d2dRouteUpdatedAtMs(route) > deletedAt;
  });
  let changed = next.length !== previous.length;

  cloudRoutes.forEach((incoming) => {
    const index = next.findIndex((route) => route.id === incoming.id);
    if (index < 0) {
      if (!changed) next = [...next];
      next.push(incoming);
      changed = true;
      return;
    }
    if (d2dRouteUpdatedAtMs(incoming) > d2dRouteUpdatedAtMs(next[index])) {
      if (!changed) next = [...next];
      next[index] = incoming;
      changed = true;
    }
  });

  return changed ? next : previous;
};

const RouteManager: React.FC<RouteManagerProps> = ({ pins, onUpdatePin }) => {
  const [routeName, setRouteName] = useState('');
  const [selectedType, setSelectedType] = useState<string | null>(null);
  const [estimatedTime, setEstimatedTime] = useState('');
  const [estimatedDistance, setEstimatedDistance] = useState('');
  const [isCalculating, setIsCalculating] = useState(false);
  const [calculatedRoute, setCalculatedRoute] = useState<RouteData | null>(null);
  const [knownRoutes, setKnownRoutes] = useState<RouteSession[]>(readLocalRoutes);
  const [activeRouteId, setActiveRouteId] = useState<string | null>(readStoredActiveRouteId);
  const [startSignal, setStartSignal] = useState(0);
  const [syncStatus, setSyncStatus] = useState(readD2DSyncStatus);

  const { getRoute, formatDuration, formatDistance } = useGoogleMapsRouting();
  const storefronts = pins.filter((pin) => pin.isStorefront);

  const getStorefrontsOfType = (type: string) => storefronts.filter((pin) => pin.storefrontType === type);

  const mergeKnownRoute = (incomingRoute: RouteSession) => {
    setKnownRoutes((previous) => {
      const index = previous.findIndex((route) => route.id === incomingRoute.id);
      if (index < 0) return [...previous, incomingRoute];
      if (d2dRouteUpdatedAtMs(previous[index]) >= d2dRouteUpdatedAtMs(incomingRoute)) return previous;
      const next = [...previous];
      next[index] = incomingRoute;
      return next;
    });
  };

  useEffect(() => subscribeD2DSyncStatus(setSyncStatus), []);

  useEffect(() => {
    let cancelled = false;
    let unsubscribeRealtime = () => undefined;

    const refresh = async (syncAuto = true) => {
      if (!navigator.onLine) return;
      try {
        const state = await loadD2DCloudRouteState({ syncAuto });
        if (!cancelled) setKnownRoutes((previous) => mergeRouteSet(previous, state.routes, state.tombstones));
      } catch (error) {
        console.error('Could not refresh route list:', error);
      }
    };

    const unsubscribeBus = subscribeD2DRoutes(
      mergeKnownRoute,
      (routeId) => setKnownRoutes((previous) => previous.filter((route) => route.id !== routeId)),
    );

    void refresh(true);
    void subscribeD2DCloudRouteChanges(() => void refresh(false))
      .then((unsubscribe) => {
        if (cancelled) unsubscribe();
        else unsubscribeRealtime = unsubscribe;
      })
      .catch((error) => console.error('Could not subscribe to realtime D2D routes:', error));

    const handleOnline = () => void refresh(true);
    window.addEventListener('online', handleOnline);
    return () => {
      cancelled = true;
      unsubscribeBus();
      unsubscribeRealtime();
      window.removeEventListener('online', handleOnline);
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const buildFallbackRoute = (routePins: HousePin[]): RouteData => {
    const orderedWaypoints = optimizeRouteOrder(routePins);
    const totalDistance = calculateRouteDistance(orderedWaypoints) * 1000;
    const walkingSeconds = totalDistance / 1000 / 5 * 3600;
    const stopSeconds = orderedWaypoints.length * 120;
    return {
      steps: [],
      totalDistance,
      totalDuration: Math.round(walkingSeconds + stopSeconds),
      geometry: orderedWaypoints.map((pin) => ({ lat: pin.lat, lng: pin.lng })),
      orderedWaypoints,
      hasUphill: false,
      hasDownhill: false,
    };
  };

  const calculateRouteEstimate = async (routePins: HousePin[]) => {
    if (routePins.length === 0) {
      setCalculatedRoute(null);
      setEstimatedTime('');
      setEstimatedDistance('');
      return null;
    }
    if (routePins.length === 1) {
      const fallback = buildFallbackRoute(routePins);
      setCalculatedRoute(fallback);
      setEstimatedTime('N/A');
      setEstimatedDistance('N/A');
      return fallback;
    }

    setIsCalculating(true);
    try {
      const googleRoute = await getRoute(routePins);
      const routeData = googleRoute || buildFallbackRoute(routePins);
      setCalculatedRoute(routeData);
      setEstimatedTime(formatDuration(routeData.totalDuration));
      setEstimatedDistance(formatDistance(routeData.totalDistance));
      return routeData;
    } catch (error) {
      console.error('Route calculation error:', error);
      const fallback = buildFallbackRoute(routePins);
      setCalculatedRoute(fallback);
      setEstimatedTime(formatDuration(fallback.totalDuration));
      setEstimatedDistance(formatDistance(fallback.totalDistance));
      return fallback;
    } finally {
      setIsCalculating(false);
    }
  };

  useEffect(() => {
    setCalculatedRoute(null);
    if (!selectedType) {
      setEstimatedTime('');
      setEstimatedDistance('');
      return;
    }
    void calculateRouteEstimate(getStorefrontsOfType(selectedType));
  // The stop set is revalidated again at creation time.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedType]);

  const createRoute = async () => {
    if (!routeName.trim()) {
      toast.error('Please enter a route name');
      return;
    }
    if (!selectedType) {
      toast.error('Please select a storefront type');
      return;
    }

    const routePins = getStorefrontsOfType(selectedType);
    if (routePins.length === 0) {
      toast.error('No matching storefronts found');
      return;
    }

    const currentIds = new Set(routePins.map((pin) => pin.id));
    const calculatedIds = new Set(calculatedRoute?.orderedWaypoints.map((pin) => pin.id) || []);
    const canReuse = Boolean(
      calculatedRoute
      && currentIds.size === calculatedIds.size
      && Array.from(currentIds).every((id) => calculatedIds.has(id)),
    );
    const routeData = canReuse
      ? calculatedRoute!
      : await calculateRouteEstimate(routePins) || buildFallbackRoute(routePins);
    const orderedPins = routeData.orderedWaypoints.length > 0 ? routeData.orderedWaypoints : optimizeRouteOrder(routePins);
    const now = new Date().toISOString();
    const routeId = `route-${Date.now()}`;

    orderedPins.forEach((pin, index) => {
      onUpdatePin(pin.id, { routeId, routeOrder: index + 1, routeTimestamp: now });
    });

    const route: RouteSession = {
      id: routeId,
      name: routeName.trim(),
      source: 'storefront',
      startTime: now,
      duration: routeData.totalDuration,
      distance: routeData.totalDistance,
      path: (routeData.geometry.length > 0 ? routeData.geometry : orderedPins.map((pin) => ({ lat: pin.lat, lng: pin.lng })))
        .map((point) => ({ ...point, timestamp: now })),
      stops: orderedPins.map((pin, index) => ({
        id: pin.id,
        address: pin.address,
        lat: pin.lat,
        lng: pin.lng,
        order: index + 1,
        status: pin.status,
      })),
      homesVisited: 0,
      totalStops: orderedPins.length,
      completedStops: 0,
      completionRate: 0,
      workedStops: 0,
      interestedStops: 0,
      quoteStops: 0,
      notInterestedStops: 0,
      completedJobs: 0,
      color: '#2563eb',
      isActive: false,
      updatedAt: now,
    };

    publishD2DRoute(route);
    toast.success(`Created route “${route.name}” with ${orderedPins.length} stops`);
    setRouteName('');
    setSelectedType(null);
    setCalculatedRoute(null);
  };

  const clearStorefrontRoutes = (type: string) => {
    const routePins = getStorefrontsOfType(type).filter((pin) => pin.routeId);
    const routeIds = Array.from(new Set(routePins.map((pin) => pin.routeId).filter(Boolean))) as string[];
    routePins.forEach((pin) => onUpdatePin(pin.id, { routeId: undefined, routeOrder: undefined, routeTimestamp: undefined }));
    routeIds.forEach(removeD2DRoute);
    toast.success('Storefront route assignments cleared');
  };

  const pinForStop = (stop: RouteStop) => pins.find((pin) => {
    if (pin.id === stop.id) return true;
    if (normalizeAddress(pin.address) === normalizeAddress(stop.address)) return true;
    return Math.abs(pin.lat - stop.lat) < 0.00002 && Math.abs(pin.lng - stop.lng) < 0.00002;
  });

  const routeMetrics = (route: RouteSession) => {
    if (route.stops?.length) {
      const stops = route.stops.map((stop) => ({ ...stop, status: pinForStop(stop)?.status || stop.status }));
      return routeProgressBreakdown(stops);
    }
    const total = route.totalStops ?? route.homesVisited ?? 0;
    const worked = route.workedStops ?? route.completedStops ?? route.homesVisited ?? 0;
    return {
      total,
      worked,
      unvisited: Math.max(0, total - worked),
      visited: 0,
      interested: route.interestedStops || 0,
      quotes: route.quoteStops || 0,
      notInterested: route.notInterestedStops || 0,
      revisitLater: route.revisitStops || 0,
      completedJobs: route.completedJobs || 0,
      workedRate: total > 0 ? worked / total * 100 : 0,
    };
  };

  const sortedRoutes = useMemo(
    () => [...knownRoutes].sort((a, b) => d2dRouteUpdatedAtMs(b) - d2dRouteUpdatedAtMs(a)),
    [knownRoutes],
  );
  const activeRoute = activeRouteId ? sortedRoutes.find((route) => route.id === activeRouteId) || null : null;

  const startRoute = (route: RouteSession) => {
    setActiveRouteId(route.id);
    setStartSignal(Date.now());
  };

  return (
    <div className="space-y-4">
      {activeRoute && (
        <ActiveRouteRunner
          route={activeRoute}
          pins={pins}
          onUpdatePin={onUpdatePin}
          startSignal={startSignal}
          onClose={() => setActiveRouteId(null)}
          onFinished={mergeKnownRoute}
        />
      )}

      <Card>
        <CardHeader className="pb-3">
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
            <CardTitle className="flex items-center gap-2"><Route className="h-5 w-5" />Unified Routes</CardTitle>
            <div className="flex gap-2">
              {!syncStatus.online && <Badge variant="destructive"><WifiOff className="mr-1 h-3 w-3" />Offline · {syncStatus.pendingKeys.length} pending</Badge>}
              {syncStatus.online && syncStatus.pendingKeys.length > 0 && <Badge variant="secondary">Syncing · {syncStatus.pendingKeys.length} pending</Badge>}
              {syncStatus.online && syncStatus.pendingKeys.length === 0 && <Badge variant="outline">Realtime connected</Badge>}
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {sortedRoutes.length === 0 ? (
            <p className="text-sm text-muted-foreground">No routes yet. A residential street appears automatically when it reaches 5 eligible pins.</p>
          ) : (
            <div className="space-y-2 max-h-[32rem] overflow-y-auto pr-1">
              {sortedRoutes.map((route) => {
                const metrics = routeMetrics(route);
                const isHistoryRun = route.source === 'gps-session' && Boolean(route.parentRouteId);
                const canStart = Boolean(route.stops?.length && !isHistoryRun);
                const isCurrent = activeRouteId === route.id;
                return (
                  <div key={route.id} className={`rounded-lg border p-3 ${isCurrent ? 'border-primary bg-primary/5' : ''}`}>
                    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <div className="font-medium truncate">{route.name}</div>
                          <Badge variant={route.source === 'auto-street' || route.autoGenerated ? 'default' : 'secondary'}>{routeSourceLabel(route)}</Badge>
                        </div>
                        <div className="mt-1 text-xs text-muted-foreground">
                          {metrics.worked}/{metrics.total} worked · {metrics.unvisited} unvisited · {metrics.interested} interested · {metrics.quotes} quotes · {metrics.completedJobs} jobs complete
                        </div>
                        <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{ width: `${Math.min(100, metrics.workedRate)}%` }} /></div>
                      </div>
                      <div className="flex shrink-0 gap-2">
                        {canStart ? (
                          <Button size="sm" onClick={() => startRoute(route)}><Navigation2 className="mr-1 h-4 w-4" />{isCurrent || readStoredActiveRouteId() === route.id ? 'Resume' : 'Start'}</Button>
                        ) : (
                          <Badge variant="outline">History only</Badge>
                        )}
                        {route.source !== 'auto-street' && !route.autoGenerated && route.source !== 'gps-session' && (
                          <Button size="icon" variant="ghost" aria-label={`Delete ${route.name}`} onClick={() => removeD2DRoute(route.id)}><Trash2 className="h-4 w-4" /></Button>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader><CardTitle className="flex items-center gap-2"><Store className="h-5 w-5" />Create Storefront Route</CardTitle></CardHeader>
        <CardContent className="space-y-4">
          <div>
            <Label htmlFor="routeName">Route Name</Label>
            <Input id="routeName" value={routeName} onChange={(event) => setRouteName(event.target.value)} placeholder="e.g. Downtown Nail Salons" />
          </div>

          <div>
            <Label className="mb-2 block">Storefront Type</Label>
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">
              {storefrontTypes.map((type) => {
                const Icon = type.icon;
                const count = getStorefrontsOfType(type.value).length;
                return (
                  <Button key={type.value} variant={selectedType === type.value ? 'default' : 'outline'} className="h-auto min-h-16 flex-col gap-1 py-2" onClick={() => setSelectedType(type.value)}>
                    <Icon className="h-4 w-4" /><span className="text-xs">{type.label}</span><span className="text-[10px] opacity-70">{count} stops</span>
                  </Button>
                );
              })}
            </div>
          </div>

          {selectedType && (
            <div className="rounded-lg border bg-muted/30 p-3 text-sm">
              <div className="flex flex-wrap items-center gap-x-4 gap-y-1">
                <span><strong>{getStorefrontsOfType(selectedType).length}</strong> storefronts</span>
                <span>Distance: <strong>{isCalculating ? 'Calculating…' : estimatedDistance || 'N/A'}</strong></span>
                <span>Time: <strong>{isCalculating ? 'Calculating…' : estimatedTime || 'N/A'}</strong></span>
                {isCalculating && <Loader2 className="h-4 w-4 animate-spin" />}
              </div>
            </div>
          )}

          <div className="flex flex-wrap gap-2">
            <Button onClick={() => void createRoute()} disabled={isCalculating || !selectedType}><Navigation2 className="mr-2 h-4 w-4" />Create Optimized Route</Button>
            {selectedType && getStorefrontsOfType(selectedType).some((pin) => pin.routeId) && (
              <Button variant="outline" onClick={() => clearStorefrontRoutes(selectedType)}><Trash2 className="mr-2 h-4 w-4" />Clear Assignments</Button>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default RouteManager;
