export interface HousePin {
  id: string;
  lat: number;
  lng: number;
  address: string;
  status: 'visited' | 'interested' | 'not-interested' | 'completed' | 'revisit-later' | 'needs-quote';
  notes: string;
  dateAdded: string;
  /** Client-side mutation timestamp used for conflict-safe cloud sync. */
  updatedAt?: string;
  /** Stable external/source identifier when a provider such as OSM supplies one. */
  externalId?: string;
  contactInfo?: string;
  beforePhoto?: string;
  afterPhoto?: string;
  customerName?: string;
  phoneNumber?: string;
  email?: string;
  routeId?: string;
  routeTimestamp?: string;
  routeOrder?: number;
  followUpDate?: string;
  followUpNote?: string;
  leadScore?: 'low' | 'medium' | 'high';
  squareFootage?: number;
  leadSource?: 'door-to-door' | 'facebook' | 'google' | 'referral' | 'website' | 'qr-code' | 'flyer' | 'ai-call' | 'other';
  isStorefront?: boolean;
  storefrontType?: 'nail-salon' | 'restaurant' | 'retail' | 'office' | 'coffee-shop' | 'hair-salon' | 'gym' | 'medical' | 'automotive' | 'other';
  businessName?: string;
  campaignId?: string;
  campaignName?: string;
  canvasserId?: string;
  canvasserName?: string;
  streetSegment?: string;
  neighborhood?: string;
  facebookProfileUrl?: string;
  facebookLeadId?: string;
  facebookCampaignName?: string;
  facebookAdSetName?: string;
  yearBuilt?: number;
  stories?: number;
  propertyType?: string;
  lotSize?: string;
  bedrooms?: number;
  bathrooms?: number;
  propertyDataSource?: 'attom' | 'bc-assessment' | 'manual';
  jobCompletedDate?: string;
  jobDetails?: string;
  serviceType?: string;
  jobValue?: number;
  isPreviousClient?: boolean;
  lastServiceDate?: string;
  serviceReminder?: boolean;
}

export type NewHousePin = Omit<HousePin, 'id'> & { id?: string };

export interface RouteStop {
  id: string;
  address: string;
  lat: number;
  lng: number;
  order: number;
  status?: string;
  streetSide?: string;
}

export type RouteSource = 'gps-session' | 'auto-street' | 'storefront' | 'manual';

export interface RouteSession {
  id: string;
  name: string;
  startTime: string;
  endTime?: string;
  duration?: number;
  distance?: number;
  path: Array<{lat: number, lng: number, timestamp: string}>;
  homesVisited: number;
  color: string;
  isActive: boolean;
  source?: RouteSource;
  routeKey?: string;
  autoGenerated?: boolean;
  city?: string;
  street?: string;
  stops?: RouteStop[];
  totalStops?: number;
  completedStops?: number;
  completionRate?: number;
  /** Stops with a canvassing outcome, distinct from completed paid jobs. */
  workedStops?: number;
  interestedStops?: number;
  quoteStops?: number;
  notInterestedStops?: number;
  revisitStops?: number;
  completedJobs?: number;
  skippedStops?: number;
  /** Original route when this row represents a completed field run/history session. */
  parentRouteId?: string;
  /** Client-side route revision timestamp used for cross-device cloud sync. */
  updatedAt?: string;
}
