
project_id = "uyyudsjqwspapmujvzmm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://997d1c18-e273-4c31-9f9c-764cd9fe584d.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
enable_signup = true

[functions]
verify_jwt = false

[functions.fetch-square-footage]
verify_jwt = false
