-- Unify auto-generated street routes and client field routes behind d2d_field_routes.
-- Auto routes remain generated from d2d_saved_routes, but are projected into each
-- authenticated user's field-route set so Map, Routes, cloud sync and history read
-- the same route model. Manual route deletion is soft-deleted conflict-safely.

alter table public.d2d_field_routes
  add column if not exists deleted_at timestamptz;

create index if not exists d2d_field_routes_user_live_updated_idx
  on public.d2d_field_routes (user_id, client_updated_at desc)
  where deleted_at is null;

create or replace function public.d2d_sync_auto_routes_for_user_id(p_user uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  r record;
  v_stops jsonb;
  v_path jsonb;
  v_completed integer;
begin
  if p_user is null then
    return;
  end if;

  for r in
    select *
    from public.d2d_saved_routes
    where auto_generated = true
      and route_key is not null
  loop
    select
      coalesce(
        jsonb_agg(
          stop.value || jsonb_build_object('order', stop.ordinality::integer)
          order by stop.ordinality
        ),
        '[]'::jsonb
      ),
      coalesce(
        jsonb_agg(
          jsonb_build_object(
            'lat', stop.value->'lat',
            'lng', stop.value->'lng',
            'timestamp', r.updated_at
          )
          order by stop.ordinality
        ),
        '[]'::jsonb
      ),
      count(*) filter (
        where lower(coalesce(stop.value->>'status', 'unvisited')) <> 'unvisited'
      )::integer
    into v_stops, v_path, v_completed
    from jsonb_array_elements(coalesce(r.route_path, '[]'::jsonb))
      with ordinality as stop(value, ordinality);

    insert into public.d2d_field_routes (
      user_id,
      client_route_id,
      route_data,
      client_updated_at,
      deleted_at,
      updated_at
    ) values (
      p_user,
      'auto:' || r.route_key,
      jsonb_build_object(
        'id', 'auto:' || r.route_key,
        'name', r.name,
        'source', 'auto-street',
        'routeKey', r.route_key,
        'autoGenerated', true,
        'city', r.city,
        'street', r.street,
        'startTime', coalesce(r.created_at, r.updated_at),
        'endTime', null,
        'duration', null,
        'distance', null,
        'path', v_path,
        'stops', v_stops,
        'homesVisited', v_completed,
        'totalStops', coalesce(r.total_houses, jsonb_array_length(v_stops)),
        'completedStops', v_completed,
        'completionRate', coalesce(r.completion_rate, 0),
        'color', '#2563eb',
        'isActive', false,
        'updatedAt', r.updated_at
      ),
      r.updated_at,
      null,
      now()
    )
    on conflict (user_id, client_route_id)
    do update set
      route_data = excluded.route_data,
      client_updated_at = excluded.client_updated_at,
      deleted_at = null,
      updated_at = now();
  end loop;

  -- If a street drops below the five-pin threshold, retire its projected route.
  update public.d2d_field_routes fr
  set
    deleted_at = now(),
    client_updated_at = greatest(fr.client_updated_at, now()),
    updated_at = now()
  where fr.user_id = p_user
    and fr.deleted_at is null
    and fr.client_route_id like 'auto:%'
    and not exists (
      select 1
      from public.d2d_saved_routes sr
      where sr.auto_generated = true
        and sr.route_key is not null
        and fr.client_route_id = 'auto:' || sr.route_key
    );
end;
$$;

revoke all on function public.d2d_sync_auto_routes_for_user_id(uuid) from public, anon, authenticated;

create or replace function public.sync_d2d_auto_routes_for_user()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  perform public.d2d_sync_auto_routes_for_user_id(v_user);
end;
$$;

revoke all on function public.sync_d2d_auto_routes_for_user() from public, anon;
grant execute on function public.sync_d2d_auto_routes_for_user() to authenticated;

create or replace function public.upsert_d2d_field_routes(p_routes jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_item jsonb;
  v_client_updated_at timestamptz;
  v_route_id text;
  v_seen_ids text[] := '{}'::text[];
begin
  if v_user is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if p_routes is null or jsonb_typeof(p_routes) <> 'array' then
    raise exception 'p_routes must be a JSON array';
  end if;

  perform public.d2d_sync_auto_routes_for_user_id(v_user);

  for v_item in select value from jsonb_array_elements(p_routes)
  loop
    v_route_id := nullif(btrim(v_item->>'client_route_id'), '');
    if v_route_id is null then
      raise exception 'Every route requires client_route_id';
    end if;

    -- Auto routes are server-owned projections. Ignore client attempts to overwrite them.
    if v_route_id like 'auto:%' then
      continue;
    end if;

    v_seen_ids := array_append(v_seen_ids, v_route_id);
    v_client_updated_at := coalesce(nullif(v_item->>'client_updated_at', '')::timestamptz, now());

    insert into public.d2d_field_routes (
      user_id,
      client_route_id,
      route_data,
      client_updated_at,
      deleted_at,
      updated_at
    ) values (
      v_user,
      v_route_id,
      coalesce(v_item->'route_data', '{}'::jsonb),
      v_client_updated_at,
      null,
      now()
    )
    on conflict (user_id, client_route_id)
    do update set
      route_data = excluded.route_data,
      client_updated_at = excluded.client_updated_at,
      deleted_at = null,
      updated_at = now()
    where public.d2d_field_routes.client_updated_at <= excluded.client_updated_at;
  end loop;

  -- The client sends its complete non-auto route set. Missing routes become tombstones,
  -- preventing a stale second device from resurrecting a deleted route later.
  update public.d2d_field_routes fr
  set
    deleted_at = now(),
    client_updated_at = now(),
    updated_at = now()
  where fr.user_id = v_user
    and fr.deleted_at is null
    and fr.client_route_id not like 'auto:%'
    and not (fr.client_route_id = any(v_seen_ids));
end;
$$;

revoke all on function public.upsert_d2d_field_routes(jsonb) from public, anon;
grant execute on function public.upsert_d2d_field_routes(jsonb) to authenticated;

create or replace function public.d2d_refresh_projected_auto_routes()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid;
begin
  for v_user in
    select user_id from public.d2d_field_routes
    union
    select user_id from public.d2d_field_pins
  loop
    perform public.d2d_sync_auto_routes_for_user_id(v_user);
  end loop;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function public.d2d_refresh_projected_auto_routes() from public, anon, authenticated;

drop trigger if exists trg_d2d_refresh_projected_auto_routes on public.d2d_saved_routes;
create trigger trg_d2d_refresh_projected_auto_routes
after insert or update or delete
on public.d2d_saved_routes
for each statement
execute function public.d2d_refresh_projected_auto_routes();

-- Backfill any users already present before this migration.
do $$
declare
  v_user uuid;
begin
  for v_user in
    select user_id from public.d2d_field_routes
    union
    select user_id from public.d2d_field_pins
  loop
    perform public.d2d_sync_auto_routes_for_user_id(v_user);
  end loop;
end;
$$;
